name: Python Package using Conda

on: 
  push:
  gollum:
  schedule:
     - cron: '30 */12 * * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: run py
      run: |
        python meituan.py
